inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

LineLength:
  Max: 170

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'
